---
#comments show standard
Cov-v0: 
  learning_starts: 10000         # 100
  learning_rate: lin_7.3e-4     # 3e-4
  buffer_size: 300000           # 1000000
  batch_size: 256               # 256
  gamma: !!float 0.9            # 0.99
  ent_coef: "auto_0.1"                # auto
  tau: 0.01                     # 0.005
  train_freq: 1                 # 1
  gradient_steps: 1             # 1
  use_sde: True


NBV-v0:
  learning_starts: 2048         # 100
  learning_rate: lin_7.3e-4     # 3e-4
  buffer_size: 300000           # 1000000
  batch_size: 256               # 256
  gamma: !!float 0.9            # 0.99
  ent_coef: 0.005                # auto
  tau: 0.01                     # 0.005
  train_freq: 1                 # 1
  gradient_steps: 1             # 1

Ins-v0:
  learning_starts: 10000         # 100
  learning_rate: lin_7.3e-4     # 3e-4
  buffer_size: 1000000           # 1000000
  batch_size: 256               # 256
  gamma: !!float 0.9            # 0.99
  ent_coef: "auto_0.1"                # auto
  tau: 0.015                     # 0.005
  train_freq: 1                 # 1
  gradient_steps: 1             # 1
  use_sde: False
  use_sde_at_warmup: False
  sde_sample_freq: 64